services:
 app-01:
    build: ./backend
    container_name: app-01
    networks:
      - internal-net-01
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-01

 app-02:
    build: ./backend
    container_name: app-02
    networks:
      - internal-net-01
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-02

 app-03:
    build: ./backend
    container_name: app-03
    networks:
      - internal-net-01
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-03
 app-04:
    build: ./backend
    container_name: app-04
    networks:
      - internal-net-02
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-04

 app-05:
    build: ./backend
    container_name: app-05
    networks:
      - internal-net-02
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-05

 app-06:
    build: ./backend
    container_name: app-06
    networks:
      - internal-net-02
    restart: unless-stopped
    environment:
      - APP_INSTANCE_NAME=app-06

 nginx-01:
    image: nginx:alpine
    container_name: internal-nginx-01
    restart: unless-stopped
    volumes:
      - ./nginx/nginx-conf-01/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-01
      - app-02
      - app-03
    networks:
      - internal-net-01
      - public-net

 nginx-02:
    image: nginx:alpine
    container_name: internal-nginx-02
    restart: unless-stopped
    volumes:
      - ./nginx/nginx-conf-02/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-04
      - app-05
      - app-06
    networks:
      - internal-net-02
      - public-net

 haproxy-lb-01:
    image: haproxy:alpine
    container_name: haproxy-lb-01
    restart: unless-stopped
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nginx-01
      - nginx-02
    networks:
      - public-net
    ports:
      - "8080:80"

 cadvisor:
   image: gcr.io/cadvisor/cadvisor:latest
   container_name: cadvisor
   privileged: true
   ports:
     - "8081:8080"
   volumes:
     - /:/rootfs:ro
     - /var/run:/var/run:ro
     - /sys:/sys:ro
     - /var/lib/docker/:/var/lib/docker:ro
     - /dev/disk/:/dev/disk:ro
   depends_on:
     - haproxy-lb-01
   networks:
     - public-net

 prometheus:
   image: prom/prometheus:latest
   container_name: prometheus
   ports:
     - "9090:9090"
   command:
     - --config.file=/etc/prometheus/prometheus.yml
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
   depends_on:
     - cadvisor
   networks:
     - public-net

networks:
  internal-net-01:
    driver: bridge
    internal: true
  internal-net-02:
    driver: bridge
    internal: true
  public-net:
    driver: bridge
