services:
 app-01:
    build: ./backend
    container_name: app-01
    networks:
      - internal-net
    restart: unless-stopped

 app-02:
    build: ./backend
    container_name: app-02
    networks:
      - internal-net
    restart: unless-stopped

 app-03:
    build: ./backend
    container_name: app-03
    networks:
      - internal-net
    restart: unless-stopped

 nginx:
    image: nginx:alpine
    container_name: internal-nginx-01
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-01
      - app-02
      - app-03
    networks:
      - internal-net
      - public-net
    ports:
      - "8080:80"

networks:
  internal-net:
    driver: bridge
    internal: true
  public-net:
    driver: bridge
